# adding columns to products and categories

# --- !Ups

ALTER TABLE Products ADD COLUMN CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP();
ALTER TABLE Tags ADD COLUMN CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP();

ALTER TABLE Products ADD COLUMN LastModified TIMESTAMP AS CURRENT_TIMESTAMP();
ALTER TABLE Tags ADD COLUMN LastModified TIMESTAMP AS CURRENT_TIMESTAMP();

ALTER TABLE Products ADD COLUMN Description CLOB;
ALTER TABLE Products ADD COLUMN Icon BLOB;

# --- !Downs

ALTER TABLE Products DROP COLUMN CreatedAt;
ALTER TABLE Tags DROP COLUMN CreatedAt;

ALTER TABLE Products DROP COLUMN LastModified;
ALTER TABLE Tags DROP COLUMN LastModified;

ALTER TABLE Products DROP COLUMN Description;
ALTER TABLE Products DROP COLUMN Icon;